[theme]
primaryColor = "#0066cc"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d26"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
